###PART 2#####
- hosts: all
  gather_facts: no
  tasks:
          - name: change ssh port to 1467
            set_fact:
                    ansible_ssh_port: 1467
          - name: install docker py
            pip:
                    name:
                            - docker
                            - docker-compose
          - name: build site
            docker_image:
                    name: site
                    dockerfile: /skillcloud-ngsite/Dockerfile-site
                    path: /skillcloud-ngsite/
                    state: build
                    tag: site
          - name: build balance
            docker_image:
                    name: balance
                    dockerfile: /skillcloud-ngsite/Dockerfile-balance
                    path: /skillcloud-ngsite/
                    state: build
                    tag: balance
          - name: run docker compose
            docker_service:
                    project_src: /skillcloud-ngsite/
                    project_name: site
