version: "3.6"

services:
        site:
                image: site:site
                container_name: site
                restart: always
                ports:
                        - 8888:80

        balance:
                image: balance:balance
                container_name: balance
                restart: always
                ports:
                        - 80:80


